name: aggregator-dockerhub

on:
  push:
    branches:
      - 'main'
    paths:
      - 'aggregator/**'
      - '.github/workflows/aggregator-dockerhub.yml'
  pull_request: # TODO: Remove (testing gh actions)
    paths:
      - 'aggregator/**'

defaults:
  run:
    working-directory: ./aggregator

env:
  DENO_VERSION: 1.x
  TEST_SECRET: ${{ env.TEST_SECRET }}
  DOCKERHUB_PASSWORD: ${{ env.DOCKERHUB_PASSWORD }}

jobs:
  push:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: denoland/setup-deno@v1
      with:
        deno-version: ${{ env.DENO_VERSION }}
    - run: echo before $TEST_SECRET after
    - run: docker login --username blswalletghactions --password $DOCKERHUB_PASSWORD
    - run: ./programs/build.ts --image-name voltrevo/bls-wallet-aggregator --image-only --also-tag-latest --push
